title: Bryan Gordley
description: Senior Software Engineer

remote_theme: piazzai/cvless

# site settings
taglong: Senior Software Engineer
tagshort: Senior Software Engineer

# author settings
author:
  name: Bryan Gordley
photo: images/bg.jpg

# profile links
profile:
  linkedin: https://www.linkedin.com/in/bgordley
  github: https://github.com/bgordley
  cv: false

# build settings
permalink: pretty
exclude:
  - LICENSE
  - Gemfile
  - vendor/
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

sass:
  sourcemap: never